export { default as Component } from './core/navigator/Component'
export { default as View } from './core/navigator/View'
export { default as Dialog } from './core/navigator/Dialog'
export { default as Navigator } from './core/navigator/Navigator'
export { default as RequestConfig } from './core/network/Request'
export { default as Request } from './core/network/Request'
export { default as DataCenter } from './game/DataCenter'
export { default as TimerService } from './game/service/TimerService'
export { default as LaunchScreenView } from './game/view/LaunchScreenView'
export { default as Utils } from './utils/utils'

import './utils/Array'
import './utils/Date'
import './utils/Number'
import './laya/laya'